### PR TITLE
Allow GorillaBot to connect to not-freenode.

### PR DESCRIPTION
**Pull request by quanticle**
Add a prompt for the server and also add a prompt for nickserv authentication.

The old pull request was old and crufty, so I closed it and recreated it.

### CODE REVIEW

**Comment by quanticle** [comment]
If you merge this branch, you can close the other PR (#59).

**Comment by molly** [comment]
I've closed #59 in favor of this PR.

However, my tests are not working with this PR. I've tried to connect to some random network (I tried EFNet, if that's relevant) and have had no success. Do you want to keep working on this or should I just close this PR?

**Comment by quanticle** [comment]
I'll continue to hack on this. It was connecting to my local IRC server. I'll have to see what efnet is doing that my local server isn't.

**Comment by molly** [comment]
🙌

**Comment by quanticle** [comment]
What were the errors that you were getting? I tried connecting to EFNet as well (the server I used was irc.scnet.net) and the bot seemed to connect just fine.

**Comment by molly** [comment]
Closing for now as abandoned. Please re-open if not!

**Pull request closed without merging**
